name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
    - main
    - development
    
# on: push    # Default will running for every branch.
    
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:

    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '17'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        # channel: 'beta' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '3.16.0' # you can also specify exact version of flutter
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    # Run widget tests for our flutter project.
    - run: flutter test
    
    # # # Build apk.
    # - run: flutter build apk --no-tree-shake-icons

    # # # Build ios.
    # - run: flutter build ios --release --no-codesign --no-tree-shake-icons
    
    # # Upload generated apk to the artifacts.
    # - uses: actions/upload-artifact@v1
    #   with:
    #     name: release-apk
    #     path: build/app/outputs/apk/release/app-release.apk

    # # Upload generated ios to the artifacts.
    # - uses: actions/upload-artifact@v1
    #   with:
    #     name: release-ios
    #     path: build/ios/iphoneos/Runner.app
